export const CREATE_POST='CREATE_POST';
export const FETCH_POST='FETCH_POST';
export const SHOW_LOADER='SHOW_LOADER';
export const HIDE_LOADER='HIDE_LOADER';
export const SHOW_MESSAGE='SHOW_MESSAGE';
export const HIDE_MESSAGE='HIDE_MESSAGE';
export const REQUEST_POSTS='REQUEST_POSTS';
